name: coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.5

      - name: Setup Nox
        uses: daisylb/setup-nox@v2.1.0

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5

      - name: Install nox-poetry
        run: pip install nox-poetry

      - name: Cache Nox environments
        uses: actions/cache@v4
        with:
          path: .nox
          key: ${{ runner.os }}-nox-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-nox

      - name: Generate coverage report
        run: nox -r -s coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.json
          slug: ChiSym/genjax
